#server:
#  port: 8080

#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: user-service
#              uri: http://localhost:8081
#              predicates:
#                - Path=/api/users/**
#            - id: activity-service
#              uri: http://localhost:8082
#              predicates:
#                - Path=/api/activities/**
server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true       # auto-route by service id
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**

            - id: activity-service
              uri: lb://ACTIVITY-SERVICE
              predicates:
                - Path=/api/activities/**


            - id: ai-service
              uri: lb://AI-SERVICE
              predicates:
                - Path=/api/recommendations/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true       # avoids the underscore-hostname issue